### ISSUE TITLE
Core tasks

### ISSUE THREAD

**Issue by starsuit** [FAC-Sixteen/dish#109]
- [x] Set up database #111 

- [x] Set up server #112 

- [x] Set up routes #120 

- [x] Handlebars templating for routes #140

- [x] Partials (header, footer) #141

- [x] Testing for server routes #149 

- [x] Database queries #142 

- [x] Build landing page menu (divided into categories: Food, Community) with an option to browse dishes #49

- [x] Create options for Food category: browse dishes, post dishes #51

- [x] Create options for Community category: browse communities, create a community #50

**Comment by dubhcait** [comment]
done
