### ISSUE TITLE
Static routes

### ISSUE THREAD

**Issue by starsuit** [FAC-Sixteen/dish#120]
- [x] route/community-info #139

- [x] route/dish-info #121

- [x] route/what-dish #122

- [x] route/register-user #123

- [x] route/add-dish #124 

- [x] route/add-community #125 

- [x] route/main #126

- [x] route/login #127

- [x] route/dish-listing #128

- [x] route/community-listing #129

- [x] route/dish-add-success #130

- [x] route/dish-add-failure #131

- [x] route/community-join-success #132

- [x] route/community-join-failure #134

- [x] route/community-add-success #133

- [x] route/community-add-failure #135

- [x] route/dish-claim-success #136

- [x] route/dish-claim-failure #137
