### ISSUE TITLE
database queries

### ISSUE THREAD

**Issue by starsuit** [FAC-Sixteen/dish#142]
- [x] DBquery dish listings #144 
- [x] DBquery community listings #145 
- [x] DBquery specific dish #146 
- [x] DBquery specific community #147
