### ISSUE TITLE
"As a user, I want to join a community so that I can meet/cook/eat with other people"

### ISSUE THREAD

**Issue by starsuit** [FAC-Sixteen/dish#15]
- [x] "I want to see a menu with the option to browse communities" #45
- [x] "I want to see a page listing available communities" #46 
- [x] "I want to click on a community to see more information on it" #47
- [x] "I want to click a button to request to join a community" #48
