### ISSUE TITLE
Listing pages functionality

### ISSUE THREAD

**Issue by starsuit** [FAC-Sixteen/dish#160]
- [ ] GET request route #82 #53 

- [ ] Route queries database #83 #54 

- [ ] Router renders data on the webpage #84 #54
