### ISSUE TITLE
"I want to click a button that submits all of my dish details"

### ISSUE THREAD

**Issue by starsuit** [FAC-Sixteen/dish#25]
- [x] Attach a Submit button to the List a Dish form #72
  - [x] Attach a POST request to the List a Dish form #73
  - [x] Create a POST route in the server to handle List a Dish data #74
  - [x] POST route sends List a Dish data to the database #75

**Comment by bobbysebolao** [comment]
All tasks complete
