### ISSUE TITLE
"I want to see a page listing the dishes available in all my communities"

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/dish#29]
- [x] Build a Listing page composed of currently available dishes #81 
  - [x] GET request route to get listing data #82 
  - [x] GET route queries database for listing data #83 
  - [x] Route sends listing data to be rendered #84

**Comment by starsuit** [comment]
all tasks complete
