### ISSUE TITLE
"I want to see a picture of the dish so I know it looks good"

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/dish#32]
- [x] GET request route to get dish data #89
  - [x] GET route queries database for dish data #90
  - [x] Route sends dish data to be rendered #91

**Comment by starsuit** [comment]
all tasks complete
