### ISSUE TITLE
"I want to see dietary info on the dish so I know if I can eat it"

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/dish#33]
- [x] GET request route to get dish data #89 
  - [x] GET route queries database for dish data #90 
  - [x] Route sends dish data to be rendered #91

**Comment by starsuit** [comment]
all tasks complete
