### ISSUE TITLE
"On the dish page, I want to click a button the claim the dish"

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/dish#34]
- [x] Button to claim the dish #92
- [x] Route to claim the dish #93
- [x] Dish claim puts user id into DB next to listing #94

**Comment by starsuit** [comment]
all tasks complete
