### ISSUE TITLE
"I want to see a confirmation message with handover details once I've claimed a dish"

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/dish#35]
- [ ] Build a confirmation message screen #104 
  - [ ] Route to confirmation message screen after claiming the dish successfully #96 
  - [ ] Display a failure message in case of Errors #79 
  - [ ] Route to failure message screen in case of dish claim error #98

**Comment by aniablaziak** [comment]
done
