### ISSUE TITLE
"I want to see a confirmation that my community has been created"

### ISSUE THREAD

**Issue by dubhcait** [FAC-Sixteen/dish#43]
- [x] Build a confirmation message screen #104 
 - [x] Route to confirmation message screen after posting the community data successfully #105 
 - [x] Display a failure message in case of Errors #79 
 - [x] Route to failure message screen in case of submit error #107
