### ISSUE TITLE
"I want to see a page listing available communities"

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/dish#46]
- [x] Build a Community Listing page #52 
    - [x] GET request route to get community data #53
    - [x] GET route queries database for community data #54
    - [x] Route sends community data to be rendered #55
