### ISSUE TITLE
"I want to click on a community to see more information on it"

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/dish#47]
- [x] Attach a set of two buttons to each currently available community #57 
  - [x] Add functionality to the buttons: 1. Allows the user to join selected community, 2. Redirects the user to a More Info page  #58 
  - [x] Route to More Info page #59 
   - [x] Build a More Info page #60 
  - [x] GET request route to get community data #61 
  - [x] GET route queries database for community data #62 
  - [x] Route sends community data to be rendered #63
