### ISSUE TITLE
"I want to click a button to request to join a community"

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/dish#48]
- [x] Attach a set of two buttons to each currently available community #57 
 - [x] Add functionality to the buttons: 1. Allows the user to join selected community, 2. Redirects the user to a More Info page #58
 - [x] Button to join the community #64 
 - [x] Route to join the community #65 
 - [x] Join request puts user id into DB next to community #66 
 - [x] Build a confirmation message screen #67 
 - [x] Route to confirmation message screen after joining the community successfully #68 
 - [x] Display a failure message in case of Errors #69 
 - [x] Route to failure message screen in case of community join error #70

**Comment by starsuit** [comment]
tasks all done
